name: Continuous Integration

"on":
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test CI workflow
        run: echo "hello, world"